[package]
name = "exercise9"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json_typegen = "0.7.0"
walkdir = "2.3.2"
